#
# Build
#

<% var files = JSON.parse(include('FILES.json')); -%>
BASIC_FILES = \
	<% files["basic"].forEach(function(path){ -%>
	<%= path %> \
	<% }); -%>
	$()
PLAIN_FILES = \
	<% files["plain"].forEach(function(path){ -%>
	<%= path %> \
	<% }); -%>
	$()
BROWSER_FILES = \
	<% files["browser_release"].forEach(function(path){ -%>
	<%= path %> \
	<% }); -%>
	$()

all: build

build: \
	package.json \
	src/development_initializer.js \
	release/biwascheme.js \
	release/biwascheme-min.js \
	release/biwascheme-plain.js \
	release/biwascheme-plain-min.js

FILES.json: FILES.json.ejs
	`npm bin`/ejs-cli FILES.json.ejs > $@

package.json: package.json.ejs FILES.json
	`npm bin`/ejs-cli package.json.ejs > $@

src/development_initializer.js: src/development_initializer.js.ejs FILES.json
	`npm bin`/ejs-cli src/development_initializer.js.ejs > $@

src/version.js: src/version.js.in VERSION
	cat $< | sed -e "s/@GIT_COMMIT@/`git log -1 --pretty=format:%H`/" | sed -e "s/@VERSION@/`cat VERSION`/" > $@

release/biwascheme.js: $(BROWSER_FILES)
	cat $(BROWSER_FILES) > $@
	@echo "Wrote " $@

release/biwascheme-min.js: release/biwascheme.js
	`npm bin`/uglifyjs -o $@ release/biwascheme.js --comments
	@echo "Wrote " $@

release/biwascheme-plain.js: $(PLAIN_FILES)
	cat $(PLAIN_FILES) > $@
	@echo "Wrote " $@

release/biwascheme-plain-min.js: release/biwascheme-plain.js
	`npm bin`/uglifyjs -o $@ release/biwascheme-plain.js --comments
	@echo "Wrote " $@

#
# Test
#

browser_test:
	cd test/browser_functions; node ./server.js

#
# Website
#

index.html: doc/_header.html index_.html doc/_footer.html
	cat doc/_header.html index_.html doc/_footer.html > index.html

website: index.html
	node bin/biwas tools/make_doc.scm

watch_website:
	ifchanged -d 'make website -B' doc/**/*.md doc/_*


